/* ===================================
   DATA-VIDEOS.JS
   Resúmenes de partidos en vídeo.
   Cargar en páginas que usen vídeos.
   =================================== */

CLUB_DATA.videos = [
  {
    id: 1,
    jornada: 1,
    titulo: 'Villarreal C.F. Vs Real Oviedo',
    fecha: '2025-08-15',
    videoId: '6t-g2jTvmoo',
  },
  {
    id: 2,
    jornada: 2,
    titulo: 'Real Oviedo Vs Real Madrid',
    fecha: '2025-08-24',
    videoId: '7J0I0utH3nA',
  },
  {
    id: 3,
    jornada: 3,
    titulo: 'Real Oviedo Vs Real Sociedad',
    fecha: '2025-08-30',
    videoId: 'thWZDrnrewI',
  },
  {
    id: 4,
    jornada: 4,
    titulo: 'Getafe C.F. Vs Real Oviedo',
    fecha: '2025-09-13',
    videoId: 'yglPhrGYXzM',
  },
  {
    id: 5,
    jornada: 5,
    titulo: 'Elche C.F. Vs Real Oviedo',
    fecha: '2025-09-21',
    videoId: '0TPftccJqsM',
  },
  {
    id: 6,
    jornada: 6,
    titulo: 'Real Oviedo Vs F.C. Barcelona',
    fecha: '2025-09-25',
    videoId: 'fo-FHUoywT8',
  },
  {
    id: 7,
    jornada: 7,
    titulo: 'Valencia C.F. Vs Real Oviedo',
    fecha: '2025-09-30',
    videoId: 'bI_704mWyu0',
  },
  {
    id: 8,
    jornada: 8,
    titulo: 'Real Oviedo Vs Levante U.D.',
    fecha: '2025-10-04',
    videoId: 'BdalQWNGtbA',
  },
  {
    id: 9,
    jornada: 9,
    titulo: 'Real Oviedo Vs R.C.D. Espanyol',
    fecha: '2025-10-17',
    videoId: 'tYdH3FakT5s',
  },
  {
    id: 10,
    jornada: 10,
    titulo: 'Girona F.C. Vs Real Oviedo',
    fecha: '2025-10-25',
    videoId: 'QeYkmRol7tI',
  },
  {
    id: 11,
    jornada: 'Copa del Rey',
    titulo: 'Ourense C.F. Vs Real Oviedo',
    fecha: '2024-10-20',
    videoId: 'v_WoJca9m2U',
  },
  {
    id: 12,
    jornada: 11,
    titulo: 'Real Oviedo Vs C.A. Osasuna',
    fecha: '2025-11-03',
    videoId: '1v8Su_KblNo',
  },
  {
    id: 13,
    jornada: 12,
    titulo: 'Athletic Club Vs Real Oviedo',
    fecha: '2025-11-09',
    videoId: 'B7l_BiWLVcA',
  },
  {
    id: 14,
    jornada: 13,
    titulo: 'Real Oviedo Vs Rayo Vallecano',
    fecha: '2025-11-23',
    videoId: '7g4nZMjdvAk',
  },
  {
    id: 15,
    jornada: 14,
    titulo: 'Atlético de Madrid Vs Real Oviedo',
    fecha: '2025-11-29',
    videoId: '9VxYdm7Y17Y',
  },
  {
    id: 16,
    jornada: 15,
    titulo: 'Real Oviedo Vs R.C.D. Mallorca',
    fecha: '2025-12-05',
    videoId: 'qxX8DMGSG6Q',
  },
  {
    id: 17,
    jornada: 16,
    titulo: 'Sevilla F.C. Vs Real Oviedo',
    fecha: '2025-12-14',
    videoId: 'YycQM9touZU',
  },
  {
    id: 18,
    jornada: 17,
    titulo: 'Real Oviedo Vs Celta de Vigo',
    fecha: '2025-12-20',
    videoId: 'gbAHcPyo5-I',
  },
  {
    id: 19,
    jornada: 18,
    titulo: 'Deportivo Alavés Vs Real Oviedo',
    fecha: '2026-01-04',
    videoId: 'VQ3KG1F5bRw',
  },
  {
    id: 20,
    jornada: 19,
    titulo: 'Real Oviedo Vs Real Betis',
    fecha: '2026-01-10',
    videoId: 'yXUf0MOa0dM',
  },
  {
    id: 21,
    jornada: 20,
    titulo: 'C.A. Osasuna Vs Real Oviedo',
    fecha: '2026-01-17',
    videoId: '4-m5NXluPwE',
  },
  {
    id: 22,
    jornada: 21,
    titulo: 'F.C. Barcelona Vs Real Oviedo',
    fecha: '2026-01-25',
    videoId: 'Nk1Ef_e3oE0',
  },
  {
    id: 23,
    jornada: 22,
    titulo: 'Real Oviedo Vs Girona F.C.',
    fecha: '2026-01-31',
    videoId: 'e7qnc7xO-ik',
  },
  {
    id: 24,
    jornada: 23,
    titulo: 'Rayo Vallecano Vs Real Oviedo',
    fecha: '2026-03-04',
    videoId: 'JzovTSBueHY',
  },
  {
    id: 25,
    jornada: 24,
    titulo: 'Real Oviedo Vs Athletic Club',
    fecha: '2026-02-15',
    videoId: '35g46UDxkTk',
  },
  {
    id: 26,
    jornada: 25,
    titulo: 'Real Sociedad Vs Real Oviedo',
    fecha: '2026-02-21',
    videoId: '35g46UDxkTk',
  },
  {
    id: 27,
    jornada: 26,
    titulo: 'Real Oviedo Vs Atlético de Madrid',
    fecha: '2026-02-28',
    videoId: '6ILV_qAvWvE',
  },
  {
    id: 28,
    jornada: 27,
    titulo: 'R.C.D. Espanyol Vs Real Oviedo',
    fecha: '2026-03-09',
    videoId: 'sB_Knf4vXts',
  },
  {
    id: 29,
    jornada: 28,
    titulo: 'Real Oviedo Vs Valencia C.F.',
    fecha: '2026-03-14',
    videoId: '5Ec3N0vmU6k',
  },
  {
    id: 30,
    jornada: 29,
    titulo: 'Levante U.D. Vs Real Oviedo',
    fecha: '2026-03-21',
    videoId: 'syuJRG2bmgg',
  },
  {
    id: 31,
    jornada: 30,
    titulo: 'Real Oviedo Vs Sevilla F.C.',
    fecha: '2026-04-05',
    videoId: 'LxGj0yYUclM',
  },
  {
    id: 32,
    jornada: 31,
    titulo: 'Celta de Vigo Vs Real Oviedo',
    fecha: '2026-04-12',
    videoId: 'SUVyA17gEY8',
  },
  {
    id: 33,
    jornada: 32,
    titulo: 'Real Oviedo Vs Elche C.F.',
    fecha: '2026-04-26',
    videoId: 'rlIVS2x6oRc',
  },
  {
    id: 34,
    jornada: 33,
    titulo: 'Real Oviedo Vs Villarreal C.F.',
    fecha: '2026-04-23',
    videoId: 'EkQ3NYZHHRE',
  },
  {
    id: 35,
    jornada: 34,
    titulo: 'Real Betis Vs Real Oviedo',
    fecha: '2026-05-03',
    videoId: 'mSncDanvuyk',
  },
  {
    id: 36,
    jornada: 35,
    titulo: 'Real Oviedo Vs Getafe C.F.',
    fecha: '2026-05-10',
    videoId: 'WXfe9-PCud4',
  },
  {
    id: 37,
    jornada: 36,
    titulo: 'Real Madrid Vs Real Oviedo',
    fecha: '2026-05-14',
    videoId: 'nWJCdYE9Oys',
  },
  {
    id: 38,
    jornada: 37,
    titulo: 'Real Oviedo Vs Deportivo Alavés',
    fecha: '2026-05-17',
    videoId: 'Mi6t96G-P1Q',
  },
  {
    id: 39,
    jornada: 38,
    titulo: 'R.C.D. Mallorca Vs Real Oviedo',
    fecha: '2026-05-23',
    videoId: 'UW8OySuv_QY',
  },
];
