/* ===================================
   DATOS DEL CLUB - REAL OVIEDO
   =================================== */

const CLUB_DATA = {
  // Información del club
  club: {
    nombre: "Real Oviedo",
    nombreCorto: "Real Oviedo",
    logo: "https://i.postimg.cc/yYcPrs6f/Oviedo.png",
    siglas: "OVI",
    fundacion: 1926,
    estadio: "Estadio Carlos Tartiere",
    capacidadEstadio: 30500,
    ciudad: "Oviedo",
    direccion: "Calle Carlos Tartiere s/n, 33013 Oviedo",
    telefono: "985 111 111",
    email: "info@realoviedo.es",
  },

  // Temporada actual (por defecto)
  temporadaActual: "2025-26",

  // Lista de temporadas disponibles
  temporadasDisponibles: [
    { id: "2025-26", nombre: "2025/26", actual: true },
    { id: "2024-25", nombre: "2024/25", actual: false },
    { id: "2023-24", nombre: "2023/24", actual: false },
    { id: "2022-23", nombre: "2022/23", actual: false },
  ],

  // ===================================
  // REGISTRO MAESTRO DE JUGADORES
  // Datos fijos que no cambian entre temporadas.
  // La función getJugadorById los fusiona automáticamente
  // con los datos variables de cada temporada.
  // ===================================
  jugadoresMaestro: {
    // ── PORTEROS ──────────────────────────────────────────────

    "aaron-escandell-banacloche": {
      nombre: "Aarón",
      apellidos: "Escandell Banacloche",
      nombreCompleto: "Aarón Escandell Banacloche",
      apodo: "Aarón",
      posicion: "Portero",
      posicionCorta: "POR",
      altura: 1.84,
      nacionalidad: ["Española"],
      lugarNacimiento: "Carcagente",
      provinciaNacimiento: "Valencia",
      fechaNacimiento: "1995-09-27",
      imagen: "https://i.postimg.cc/hvxDQPg1/Aarón_PNG_(3).webp",
    },

    "horatiu-alexandru-moldovan": {
      nombre: "Horațiu Alexandru",
      apellidos: "Moldovan",
      nombreCompleto: "Horațiu Alexandru Moldovan",
      apodo: "Moldovan",
      posicion: "Portero",
      posicionCorta: "POR",
      altura: 1.86,
      nacionalidad: ["Rumana"],
      lugarNacimiento: "Cluj-Napoca",
      provinciaNacimiento: "Cluj",
      fechaNacimiento: "1998-01-20",
      imagen: "https://i.postimg.cc/sgPM0mk4/Moldovan_PNG_(2).webp",
      seleccion: {
        pais: "Rumanía",
        bandera: "https://flagcdn.com/16x12/ro.webp",
        datos: [
          {
            categoria: "Absoluta",
            partidos: 16,
            goles: 17,
            asistencias: 0,
            minutos: 1440,
            amarillas: 0,
            rojas: 0,
          },
          {
            categoria: "U21",
            partidos: 0,
            goles: 0,
            asistencias: 0,
            minutos: 0,
            amarillas: 0,
            rojas: 0,
          },
        ],
      },
    },

    "miguel-de-jesus-narvaez-lopez": {
      nombre: "Miguel de Jesús",
      apellidos: "Narváez López",
      nombreCompleto: "Miguel de Jesús Narváez López",
      apodo: "Narváez",
      posicion: "Portero",
      posicionCorta: "POR",
      altura: 1.88,
      nacionalidad: ["Española"],
      lugarNacimiento: "Badajoz",
      provinciaNacimiento: "Badajoz",
      fechaNacimiento: "2002-04-29",
      imagen: "https://i.postimg.cc/XJqXqbps/Narváez_PNG.webp",
    },

    "victor-marquez": {
      nombre: "Víctor",
      apellidos: "Márquez López",
      nombreCompleto: "Víctor Márquez",
      posicion: "Defensa",
      posicionCorta: "DC",
      altura: 1.82,
      nacionalidad: "Española",
      lugarNacimiento: "León",
      fechaNacimiento: "1997-09-30",
      imagen: "https://picsum.photos/seed/victor-marquez/400/500",
    },

    "sergio-nunez": {
      nombre: "Sergio",
      apellidos: "Núñez Pérez",
      nombreCompleto: "Sergio Núñez",
      posicion: "Lateral Izquierdo",
      posicionCorta: "LI",
      altura: 1.76,
      nacionalidad: "Española",
      lugarNacimiento: "Madrid",
      fechaNacimiento: "2000-02-14",
      imagen: "https://picsum.photos/seed/sergio-nunez/400/500",
    },

    // ── DEFENSAS ──────────────────────────────────────────────

    "eric-bertrand-bailly": {
      nombre: "Eric Bertrand",
      apellidos: "Bailly",
      nombreCompleto: "Eric Bertrand Bailly",
      apodo: "Bailly",
      posicion: "Defensa",
      posicionCorta: "DC",
      altura: 1.87,
      nacionalidad: ["Costamarfileña"],
      lugarNacimiento: "Bingerville",
      provinciaNacimiento: "Abiyán",
      fechaNacimiento: "1994-04-12",
      imagen: "https://i.postimg.cc/qRHtqnX7/Bailly_PNG_(2).webp",
      seleccion: {
        pais: "Costa de Marfil",
        bandera: "https://flagcdn.com/16x12/ci.png",
        datos: [
          {
            categoria: "Absoluta",
            partidos: 48,
            goles: 2,
            asistencias: 1,
            minutos: 4024,
            amarillas: 11,
            rojas: 0,
          },
          {
            categoria: "U23",
            partidos: 4,
            goles: 1,
            asistencias: 0,
            minutos: 390,
            amarillas: 0,
            rojas: 0,
          },
        ],
      },
    },

    "abdel-rahim-alhassane-bonkano": {
      nombre: "Abdel Rahim",
      apellidos: "Alhassane Bonkano",
      nombreCompleto: "Abdel Rahim Alhassane Bonkano",
      apodo: "Rahim",
      posicion: "Defensa",
      posicionCorta: "DC",
      altura: 1.84,
      nacionalidad: ["Nigerina", "Española"],
      lugarNacimiento: "Abuja",
      provinciaNacimiento: "Abuja",
      fechaNacimiento: "2002-01-01",
      imagen: "https://i.postimg.cc/RCdpXtNX/Rahim.webp",
      seleccion: {
        pais: "Níger",
        bandera: "https://flagcdn.com/16x12/ne.webp",
        datos: [
          {
            categoria: "Absoluta",
            partidos: 23,
            goles: 2,
            asistencias: 3,
            minutos: 1962,
            amarillas: 2,
            rojas: 0,
          },
          {
            categoria: "U23",
            partidos: 3,
            goles: 0,
            asistencias: 0,
            minutos: 270,
            amarillas: 1,
            rojas: 0,
          },
          {
            categoria: "U20",
            partidos: 0,
            goles: 0,
            asistencias: 0,
            minutos: 0,
            amarillas: 0,
            rojas: 0,
          },
        ],
      },
    },

    "david-costas-cordal": {
  nombre: "David",
  apellidos: "Costas Cordal",
  nombreCompleto: "David Costas Cordal",
  apodo: "David Costas",
  posicion: "Defensa",
  posicionCorta: "DC",
  altura: 1.84,
  nacionalidad: [],
  lugarNacimiento: "Chapela",
  provinciaNacimiento: "Pontevedra",
  fechaNacimiento: "1995-03-26",
  imagen: "https://i.postimg.cc/V6ScxHbr/David-Costas-PNG.webp",
  seleccion: {
    pais: "España",
    bandera: "es",
    datos: [
      {
        categoria: "Sub-21",
        partidos: 1,
        goles: 0,
        asistencias: 0,
        minutos: 65,
        amarillas: 0,
        rojas: 0,
      }
    ],
  },
}

    "daniel-pedro-calvo-san-roman": {
      nombre: "Daniel Pedro",
      apellidos: "Calvo San Román",
      nombreCompleto: "Daniel Pedro Calvo San Román",
      posicion: "Defensa",
      posicionCorta: "DC",
      altura: 1.93,
      nacionalidad: "Española",
      lugarNacimiento: "Huesca, Huesca",
      fechaNacimiento: "1994-04-01",
      imagen: "https://i.postimg.cc/Wb0spKY0/Dani_Calvo_PNG.webp",
    },

    "borja-trujillo": {
      nombre: "Borja",
      apellidos: "Trujillo Fernández",
      nombreCompleto: "Borja Trujillo",
      posicion: "Central",
      posicionCorta: "DC",
      altura: 1.88,
      peso: 83,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Gijón, Asturias",
      fechaNacimiento: "1999-08-05",
      imagen: "https://picsum.photos/seed/df5-24/400/500",
      redes: { instagram: "#", twitter: null },
    },

    "raul-fernandez": {
      nombre: "Raúl",
      apellidos: "Fernández Soto",
      nombreCompleto: "Raúl Fernández",
      posicion: "Central",
      posicionCorta: "DC",
      altura: 1.84,
      peso: 79,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Gijón, Asturias",
      fechaNacimiento: "1993-02-14",
      imagen: "https://picsum.photos/seed/df3-22/400/500",
      fallecido: true,
      fechaFallecimiento: "2024-05-15",
      redes: { instagram: "#", twitter: "#" },
    },

    "jorge-martin": {
      nombre: "Jorge",
      apellidos: "Martín Díaz",
      nombreCompleto: "Jorge Martín",
      posicion: "Lateral Izquierdo",
      posicionCorta: "LI",
      peso: 71,
      pie: "Izquierdo",
      nacionalidad: "Española",
      lugarNacimiento: "Zamora",
      fechaNacimiento: "1998-11-30",
      imagen: "https://picsum.photos/seed/df4-22/400/500",
      redes: { instagram: "#", twitter: null },
    },

    // ── CENTROCAMPISTAS ───────────────────────────────────────

    "alvaro-santos": {
      nombre: "Álvaro",
      apellidos: "Santos Díaz",
      nombreCompleto: "Álvaro Santos",
      posicion: "Mediocentro Defensivo",
      posicionCorta: "MCD",
      altura: 1.8,
      peso: 75,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Sevilla",
      fechaNacimiento: "1994-12-10",
      imagen: "https://picsum.photos/seed/mf1-24/400/500",
      redes: { instagram: "#", twitter: "#" },
    },

    "nacho-ruiz": {
      nombre: "Nacho",
      apellidos: "Ruiz Martínez",
      nombreCompleto: "Nacho Ruiz",
      posicion: "Centrocampista",
      posicionCorta: "MC",
      altura: 1.77,
      peso: 72,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Valencia",
      fechaNacimiento: "1998-04-25",
      imagen: "https://picsum.photos/seed/mf2-24/400/500",
      redes: { instagram: "#", twitter: "#" },
    },

    "pedro-leal": {
      nombre: "Pedro",
      apellidos: "Leal García",
      nombreCompleto: "Pedro Leal",
      posicion: "Mediapunta",
      posicionCorta: "MP",
      altura: 1.74,
      peso: 68,
      pie: "Izquierdo",
      nacionalidad: "Española",
      lugarNacimiento: "Barcelona",
      fechaNacimiento: "1996-07-08",
      imagen: "https://picsum.photos/seed/mf3-24/400/500",
      redes: { instagram: "#", twitter: "#" },
    },

    "ivan-pacheco": {
      nombre: "Iván",
      apellidos: "Pacheco Fernández",
      nombreCompleto: "Iván Pacheco",
      posicion: "Centrocampista",
      posicionCorta: "MC",
      altura: 1.75,
      peso: 70,
      pie: "Izquierdo",
      nacionalidad: "Española",
      lugarNacimiento: "Salamanca",
      fechaNacimiento: "2001-03-18",
      imagen: "https://picsum.photos/seed/mf4-24/400/500",
      redes: { instagram: "#", twitter: null },
    },

    "antonio-suarez": {
      nombre: "Antonio",
      apellidos: "Suárez Vega",
      nombreCompleto: "Antonio Suárez",
      posicion: "Centrocampista",
      posicionCorta: "MC",
      altura: 1.8,
      peso: 75,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Zamora",
      fechaNacimiento: "1998-09-22",
      imagen: "https://picsum.photos/seed/mf5-24/400/500",
      redes: { instagram: "#", twitter: "#" },
    },

    // ── DELANTEROS ────────────────────────────────────────────

    "javi-martinez": {
      nombre: "Javi",
      apellidos: "Martínez Fernández",
      nombreCompleto: "Javi Martínez",
      posicion: "Delantero Centro",
      posicionCorta: "DC",
      altura: 1.82,
      peso: 75,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Gijón, Asturias",
      fechaNacimiento: "1997-03-15",
      imagen: "https://picsum.photos/seed/fw1-24/400/500",
      redes: { instagram: "#", twitter: "#" },
      seleccion: {
        pais: "España",
        bandera: "https://flagcdn.com/w40/es.png",
        datos: [
          { categoria: "Absoluta", partidos: 28, goles: 3 },
          { categoria: "U21", partidos: 15, goles: 2 },
        ],
      },
    },

    "ruben-cano": {
      nombre: "Rubén",
      apellidos: "Cano Pérez",
      nombreCompleto: "Rubén Cano",
      posicion: "Extremo Derecho",
      posicionCorta: "ED",
      altura: 1.73,
      peso: 67,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Bilbao, Vizcaya",
      fechaNacimiento: "1999-05-28",
      imagen: "https://picsum.photos/seed/fw2-24/400/500",
      redes: { instagram: "#", twitter: null },
    },

    "luis-garcia": {
      nombre: "Luis",
      apellidos: "García Rodríguez",
      nombreCompleto: "Luis 'Lucho' García",
      posicion: "Extremo Izquierdo",
      posicionCorta: "EI",
      altura: 1.76,
      peso: 71,
      pie: "Izquierdo",
      nacionalidad: "Argentino",
      lugarNacimiento: "Buenos Aires",
      fechaNacimiento: "2000-09-18",
      imagen: "https://picsum.photos/seed/fw3-24/400/500",
      redes: { instagram: "#", twitter: "#" },
    },

    "diego-lopez": {
      nombre: "Diego",
      apellidos: "López Sánchez",
      nombreCompleto: "Diego 'Chicho' López",
      posicion: "Delantero",
      posicionCorta: "DC",
      altura: 1.79,
      peso: 76,
      pie: "Derecho",
      nacionalidad: "Española",
      lugarNacimiento: "Santander, Cantabria",
      fechaNacimiento: "2002-01-05",
      imagen: "https://picsum.photos/seed/fw4-24/400/500",
      redes: { instagram: "#", twitter: null },
    },
  }, // fin jugadoresMaestro

  // ===================================
  // DATOS POR TEMPORADA
  // Solo se incluyen aquí los campos VARIABLES:
  //   codigo (obligatorio — clave de enlace con jugadoresMaestro)
  //   id     (alias de codigo, mantenido por compatibilidad)
  //   dorsal, enClubDesde, contratoHasta
  //   esCapitan, logros (si aplica esa temporada)
  //   stats  (estadísticas de la temporada)
  //   partidos (lista de partidos jugados)
  // ===================================
  temporadas: {
    // ===================================
    // TEMPORADA 2025/26
    // ===================================
    "2025-26": {
      competicion: "Primera División",
      grupo: "null",

      estadisticasEquipo: {
        posicion: 20,
        partidosJugados: 30,
        victorias: 5,
        empates: 9,
        derrotas: 16,
        golesFavor: 21,
        golesContra: 48,
      },

      jugadores: [
        // PORTEROS
        {
          id: "aaron-escandell-banacloche",
          codigo: "aaron-escandell-banacloche",
          dorsal: 13,
          enClubDesde: "2024",
          contratoHasta: "2027",
          stats: {
            partidos: 31,
            goles: 48,
            asistencias: 0,
            minutos: 2790,
            amarillas: 2,
            rojas: 0,
            desglose: {
              "Primera División": {
                partidos: 30,
                goles: 48,
                asistencias: 0,
                minutos: 2700,
                amarillas: 2,
                rojas: 0,
              },
              "Copa del Rey": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
              "Competición Internacional": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
            },
          },
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-15",
              local: "Villarreal C.F.",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Oviedo",
              visitante: "Real Madrid",
              golesLocal: 0,
              golesVisitante: 3,
              resultado: "D",
              minutos: 90,
              goles: 3,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-30",
              local: "Real Oviedo",
              visitante: "Real Sociedad",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: 4,
              competicion: "Primera División",
              fecha: "2025-09-13",
              local: "Getafe C.F.",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 5,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Elche C.F.",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 6,
              competicion: "Primera División",
              fecha: "2025-09-25",
              local: "Real Oviedo",
              visitante: "F.C. Barcelona",
              golesLocal: 1,
              golesVisitante: 3,
              resultado: "D",
              minutos: 90,
              goles: 3,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-09-30",
              local: "Valencia C.F.",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 8,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-04",
              local: "Real Oviedo",
              visitante: "Levante U.D.",
              golesLocal: 0,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 9,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-17",
              local: "Real Oviedo",
              visitante: "R.C.D. Espanyol",
              golesLocal: 0,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: 10,
              competicion: "Primera División",
              fecha: "2025-10-25",
              local: "Girona F.C.",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 3,
              resultado: "E",
              minutos: 90,
              goles: 3,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-03",
              local: "Real Oviedo",
              visitante: "C.A. Osasuna",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 12,
              jornada: 12,
              competicion: "Primera División",
              fecha: "2025-11-09",
              local: "Athletic Club",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 13,
              jornada: 13,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 14,
              competicion: "Primera División",
              fecha: "2025-11-29",
              local: "Atlético de Madrid",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-05",
              local: "Real Oviedo",
              visitante: "R.C.D. Mallorca",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 16,
              jornada: 16,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Sevilla F.C.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 4,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2025-12-20",
              local: "Real Oviedo",
              visitante: "R.C. Celta de Vigo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 18,
              jornada: 18,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Deportivo Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 19,
              jornada: 19,
              competicion: "Primera División",
              fecha: "2026-01-10",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 20,
              jornada: 20,
              competicion: "Primera División",
              fecha: "2026-01-17",
              local: "C.A. Osasuna",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 3,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 21,
              jornada: 21,
              competicion: "Primera División",
              fecha: "2026-01-25",
              local: "F.C. Barcelona",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 3,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 22,
              jornada: 22,
              competicion: "Primera División",
              fecha: "2026-01-31",
              local: "Real Oviedo",
              visitante: "Girona F.C.",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 23,
              jornada: 23,
              competicion: "Primera División",
              fecha: "2026-03-04",
              local: "Rayo Vallecano",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 3,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 24,
              jornada: 24,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Athletic Club",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 25,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-02-21",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 3,
              resultado: "E",
              minutos: 90,
              goles: 3,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 26,
              jornada: 26,
              competicion: "Primera División",
              fecha: "2026-02-28",
              local: "Real Oviedo",
              visitante: "Atlético de Madrid",
              golesLocal: 0,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 27,
              jornada: 27,
              competicion: "Primera División",
              fecha: "2026-03-09",
              local: "R.C.D. Espanyol",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 28,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-14",
              local: "Real Oviedo",
              visitante: "Valencia C.F.",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 29,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-21",
              local: "Levante U.D.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 4,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 30,
              jornada: 30,
              competicion: "Primera División",
              fecha: "2026-04-05",
              local: "Real Oviedo",
              visitante: "Sevilla F.C.",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 31,
              jornada: 31,
              competicion: "Primera División",
              fecha: "2026-04-12",
              local: "R.C. Celta de Vigo",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 3,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
        },
        {
          id: "horatiu-alexandru-moldovan",
          codigo: "horatiu-alexandru-moldovan",
          dorsal: 1,
          enClubDesde: "2025",
          contratoHasta: "2026",
          stats: {
            partidos: 1,
            goles: 4,
            asistencias: 0,
            minutos: 120,
            amarillas: 0,
            rojas: 0,
            desglose: {
              "Primera División": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
              "Copa del Rey": {
                partidos: 1,
                goles: 4,
                asistencias: 0,
                minutos: 120,
                amarillas: 0,
                rojas: 0,
              },
              "Competición Internacional": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
            },
          },
          partidos: [
            {
              id: 1,
              jornada: "Primera Ronda",
              competicion: "Copa del Rey",
              fecha: "2025-10-28",
              local: "Ourense C.F.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 120,
              goles: 4,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
        },
        {
          id: "miguel-de-jesus-narvaez-lopez",
          codigo: "miguel-de-jesus-narvaez-lopez",
          dorsal: 26,
          enClubDesde: "2024",
          contratoHasta: "2027",
          stats: {
            partidos: 0,
            goles: 0,
            asistencias: 0,
            minutos: 0,
            amarillas: 0,
            rojas: 0,
            desglose: {
              "Primera División": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
              "Copa del Rey": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
              "Competición Internacional": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
            },
          },
          partidos: [],
        },
        // DEFENSAS
        {
          id: "eric-bertrand-bailly",
          codigo: "eric-bertrand-bailly",
          dorsal: 2,
          posicion: "Central",
          enClubDesde: "2025",
          contratoHasta: "2027",
          stats: {
            partidos: 11,
            goles: 1,
            asistencias: 0,
            minutos: 1074,
            amarillas: 3,
            rojas: 0,
            desglose: {
              "Primera División": {
                partidos: 11,
                goles: 1,
                asistencias: 0,
                minutos: 954,
                amarillas: 3,
                rojas: 0,
              },
              "Copa del Rey": {
                partidos: 1,
                goles: 0,
                asistencias: 0,
                minutos: 120,
                amarillas: 0,
                rojas: 0,
              },
              "Competición Internacional": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
            },
          },
          partidos: [
            {
              id: 1,
              jornada: 6,
              competicion: "Primera División",
              fecha: "2025-09-25",
              local: "Real Oviedo",
              visitante: "F.C. Barcelona",
              golesLocal: 1,
              golesVisitante: 3,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 2,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-04",
              local: "Real Oviedo",
              visitante: "Levante U.D.",
              golesLocal: 0,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-17",
              local: "Real Oviedo",
              visitante: "R.C.D. Espanyol",
              golesLocal: 0,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: "Primera Ronda",
              competicion: "Copa del Rey",
              fecha: "2025-10-28",
              local: "Ourense C.F.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 120,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 5,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2025-12-20",
              local: "Real Oviedo",
              visitante: "R.C. Celta de Vigo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 18,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Deportivo Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 54,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 24,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Athletic Club",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 8,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-02-21",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 3,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 9,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-14",
              local: "Real Oviedo",
              visitante: "Valencia C.F.",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-21",
              local: "Levante U.D.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 11,
              jornada: 30,
              competicion: "Primera División",
              fecha: "2026-04-05",
              local: "Real Oviedo",
              visitante: "Sevilla F.C.",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 12,
              jornada: 31,
              competicion: "Primera División",
              fecha: "2026-04-12",
              local: "R.C. Celta de Vigo",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 3,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],

        },
        {
          id: "abdel-rahim-alhassane-bonkano",
          codigo: "abdel-rahim-alhassane-bonkano",
          dorsal: 3,
          posicion: "Lateral Izquierdo",
          enClubDesde: "2024",
          contratoHasta: "2028",
          stats: {
            partidos: 23,
            goles: 0,
            asistencias: 0,
            minutos: 1515,
            amarillas: 3,
            rojas: 0,
            desglose: {
              "Primera División": {
                partidos: 22,
                goles: 0,
                asistencias: 0,
                minutos: 1451,
                amarillas: 2,
                rojas: 0,
              },
              "Copa del Rey": {
                partidos: 1,
                goles: 0,
                asistencias: 0,
                minutos: 64,
                amarillas: 1,
                rojas: 0,
              },
              "Competición Internacional": {
                partidos: 0,
                goles: 0,
                asistencias: 0,
                minutos: 0,
                amarillas: 0,
                rojas: 0,
              },
            },
          },
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-15",
              local: "Villarreal C.F.",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 85,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Oviedo",
              visitante: "Real Madrid",
              golesLocal: 0,
              golesVisitante: 3,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-30",
              local: "Real Oviedo",
              visitante: "Real Sociedad",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: "4",
              competicion: "Primera División",
              fecha: "2025-09-13",
              local: "Getafe C.F.",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 25,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 5,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Elche C.F.",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 6,
              competicion: "Primera División",
              fecha: "2025-09-25",
              local: "Real Oviedo",
              visitante: "F.C. Barcelona",
              golesLocal: 1,
              golesVisitante: 3,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-09-30",
              local: "Valencia C.F.",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 8,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-04",
              local: "Real Oviedo",
              visitante: "Levante U.D.",
              golesLocal: 0,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 9,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-17",
              local: "Real Oviedo",
              visitante: "R.C.D. Espanyol",
              golesLocal: 0,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: 10,
              competicion: "Primera División",
              fecha: "2025-10-25",
              local: "Girona F.C.",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 3,
              resultado: "E",
              minutos: 14,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: "Primera Ronda",
              competicion: "Copa del Rey",
              fecha: "2025-10-28",
              local: "Ourense C.F.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 64,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 12,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-03",
              local: "Real Oviedo",
              visitante: "C.A. Osasuna",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 4,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 13,
              jornada: 13,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 45,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 14,
              competicion: "Primera División",
              fecha: "2025-11-29",
              local: "Atlético de Madrid",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-05",
              local: "Real Oviedo",
              visitante: "R.C.D. Mallorca",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 16,
              jornada: 16,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Sevilla F.C.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 0,
              resultado: "D",
              minutos: 70,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2025-12-20",
              local: "Real Oviedo",
              visitante: "R.C. Celta de Vigo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 18,
              jornada: 18,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Deportivo Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 19,
              jornada: 19,
              competicion: "Primera División",
              fecha: "2026-01-10",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 20,
              jornada: 20,
              competicion: "Primera División",
              fecha: "2026-01-17",
              local: "C.A. Osasuna",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 21,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-21",
              local: "Levante U.D.",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 26,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 22,
              jornada: 30,
              competicion: "Primera División",
              fecha: "2026-04-05",
              local: "Real Oviedo",
              visitante: "Sevilla F.C.",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 5,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 23,
              jornada: 31,
              competicion: "Primera División",
              fecha: "2026-04-12",
              local: "R.C. Celta de Vigo",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 3,
              resultado: "V",
              minutos: 7,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
          ],
        },
        {
          id: "victor-marquez",
          codigo: "victor-marquez",
          dorsal: 5,
          enClubDesde: "2023",
          contratoHasta: "2026",
          stats: {
            partidos: 22,
            goles: 1,
            asistencias: 2,
            minutos: 1890,
            amarillas: 4,
            rojas: 0,
          },
        },
        {
          id: "sergio-nunez",
          codigo: "sergio-nunez",
          dorsal: 3,
          enClubDesde: "2024",
          contratoHasta: "2026",
          stats: {
            partidos: 18,
            goles: 0,
            asistencias: 4,
            minutos: 1420,
            amarillas: 2,
            rojas: 0,
          },
        },
        {
          id: "borja-trujillo",
          codigo: "borja-trujillo",
          dorsal: 15,
          enClubDesde: "2023",
          contratoHasta: "2025",
          stats: {
            partidos: 12,
            goles: 0,
            asistencias: 0,
            minutos: 890,
            amarillas: 2,
            rojas: 0,
          },
        },
        {
          id: "alvaro-santos",
          codigo: "alvaro-santos",
          dorsal: 6,
          enClubDesde: "2022",
          contratoHasta: "2025",
          stats: {
            partidos: 23,
            goles: 1,
            asistencias: 2,
            minutos: 1980,
            amarillas: 8,
            rojas: 0,
          },
        },
        {
          id: "nacho-ruiz",
          codigo: "nacho-ruiz",
          dorsal: 8,
          enClubDesde: "2023",
          contratoHasta: "2026",
          stats: {
            partidos: 22,
            goles: 5,
            asistencias: 6,
            minutos: 1750,
            amarillas: 3,
            rojas: 0,
          },
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-17",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-31",
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 2,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 5,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-10-05",
              local: "Real Oviedo",
              visitante: "Getafe CF",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 75,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-19",
              local: "Valencia CF",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-26",
              local: "Real Oviedo",
              visitante: "R.C. Celta de Vigo",
              golesLocal: 2,
              golesVisitante: 2,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 8,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-09",
              local: "Real Oviedo",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 4,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 9,
              jornada: 12,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: "Octavos",
              competicion: "Copa del Rey",
              fecha: "2025-11-06",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Real Oviedo",
              visitante: "Espanyol",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 12,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 13,
              jornada: 22,
              competicion: "Primera División",
              fecha: "2026-02-08",
              local: "Getafe CF",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 68,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 23,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Valencia CF",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-03-01",
              local: "Real Oviedo",
              visitante: "Villarreal CF",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 16,
              jornada: 27,
              competicion: "Primera División",
              fecha: "2026-03-15",
              local: "Real Oviedo",
              visitante: "Alavés",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-22",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 18,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-29",
              local: "Levante UD",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
        },
        {
          id: "pedro-leal",
          codigo: "pedro-leal",
          dorsal: 10,
          enClubDesde: "2022",
          contratoHasta: "2025",
          stats: {
            partidos: 21,
            goles: 8,
            asistencias: 5,
            minutos: 1680,
            amarillas: 2,
            rojas: 0,
          },
        },
        {
          id: "ivan-pacheco",
          codigo: "ivan-pacheco",
          dorsal: 16,
          enClubDesde: "2025",
          contratoHasta: "2027",
          stats: {
            partidos: 5,
            goles: 0,
            asistencias: 1,
            minutos: 210,
            amarillas: 0,
            rojas: 0,
          },
        },
        {
          id: "antonio-suarez",
          codigo: "antonio-suarez",
          dorsal: 14,
          enClubDesde: "2023",
          contratoHasta: "2025",
          stats: {
            partidos: 15,
            goles: 2,
            asistencias: 3,
            minutos: 1100,
            amarillas: 3,
            rojas: 0,
          },
        },
        {
          id: "javi-martinez",
          codigo: "javi-martinez",
          dorsal: 9,
          enClubDesde: "2022",
          contratoHasta: "2026",
          esCapitan: true,
          logros: ["Pichichi Primera RFEF 2023/24", "Capitán del equipo"],
          stats: {
            partidos: 23,
            goles: 14,
            asistencias: 4,
            minutos: 1892,
            amarillas: 4,
            rojas: 0,
          },
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-17",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-31",
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 2,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: 4,
              competicion: "Primera División",
              fecha: "2025-09-14",
              local: "Athletic Club",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 5,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 6,
              competicion: "Primera División",
              fecha: "2025-09-28",
              local: "Osasuna",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 0,
              resultado: "D",
              minutos: 72,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-10-05",
              local: "Real Oviedo",
              visitante: "Getafe CF",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 8,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-19",
              local: "Valencia CF",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 9,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-26",
              local: "Real Oviedo",
              visitante: "R.C. Celta de Vigo",
              golesLocal: 2,
              golesVisitante: 2,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: "Octavos",
              competicion: "Copa del Rey",
              fecha: "2025-11-06",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-09",
              local: "Real Oviedo",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 4,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 12,
              jornada: 12,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: true,
              roja: false,
            },
            {
              id: 13,
              jornada: 14,
              competicion: "Primera División",
              fecha: "2025-12-07",
              local: "Atlético Madrid",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Real Oviedo",
              visitante: "Espanyol",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 16,
              jornada: 22,
              competicion: "Primera División",
              fecha: "2026-02-08",
              local: "Getafe CF",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 23,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Valencia CF",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 18,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-03-01",
              local: "Real Oviedo",
              visitante: "Villarreal CF",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 78,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 19,
              jornada: 27,
              competicion: "Primera División",
              fecha: "2026-03-15",
              local: "Real Oviedo",
              visitante: "Alavés",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 20,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-22",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 21,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-29",
              local: "Levante UD",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
        },
        {
          id: "ruben-cano",
          codigo: "ruben-cano",
          dorsal: 7,
          enClubDesde: "2023",
          contratoHasta: "2025",
          stats: {
            partidos: 20,
            goles: 6,
            asistencias: 8,
            minutos: 1450,
            amarillas: 1,
            rojas: 0,
          },
        },
        {
          id: "luis-garcia",
          codigo: "luis-garcia",
          dorsal: 11,
          enClubDesde: "2024",
          contratoHasta: "2026",
          stats: {
            partidos: 22,
            goles: 7,
            asistencias: 9,
            minutos: 1580,
            amarillas: 2,
            rojas: 0,
          },
        },
        {
          id: "diego-lopez",
          codigo: "diego-lopez",
          dorsal: 17,
          enClubDesde: "2024",
          contratoHasta: "2026",
          stats: {
            partidos: 12,
            goles: 3,
            asistencias: 1,
            minutos: 580,
            amarillas: 0,
            rojas: 0,
          },
        },
      ],

      cuerpoTecnico: [
        {
          id: 1,
          nombre: "Carlos Mendoza",
          cargo: "Entrenador Principal",
          imagen: "https://picsum.photos/seed/coach1/400/450",
          descripcion:
            "Licenciado en Educación Física con más de 15 años de experiencia.",
          esPrincipal: true,
          estadisticas: {
            partidos: 89,
            victorias: 46,
            empates: 22,
            derrotas: 21,
          },
        },
        {
          id: 2,
          nombre: "Roberto Vázquez",
          cargo: "Segundo Entrenador",
          imagen: "https://picsum.photos/seed/coach2/400/450",
          descripcion: "Especialista en análisis táctico.",
          esPrincipal: false,
        },
      ],

      partidosJugados: [
        {
          id: 1,
          jornada: 23,
          competicion: "Primera División",
          fecha: "2025-01-19",
          local: "Real Oviedo",
          visitante: "Atlético Vergara",
          golesLocal: 2,
          golesVisitante: 1,
          resultado: "V",
        },
        {
          id: 2,
          jornada: "Octavos",
          competicion: "Copa del Rey",
          fecha: "2025-01-15",
          local: "Real Oviedo",
          visitante: "Sevilla FC",
          golesLocal: 1,
          golesVisitante: 0,
          resultado: "V",
        },
      ],
    },

    // ===================================
    // TEMPORADA 2023/24
    // ===================================
    "2023-24": {
      competicion: "Primera RFEF",
      grupo: "Grupo I",

      estadisticasEquipo: {
        posicion: 4,
        partidosJugados: 38,
        victorias: 18,
        empates: 10,
        derrotas: 10,
        golesFavor: 56,
        golesContra: 35,
      },

      jugadores: [
        {
          id: "miguel-angel-torres",
          codigo: "miguel-angel-torres",
          dorsal: 1,
          enClubDesde: "2022",
          contratoHasta: "2025",
          stats: {
            partidos: 36,
            goles: 0,
            asistencias: 0,
            minutos: 3240,
            amarillas: 3,
            rojas: 0,
          },
        },
        {
          id: "javi-martinez",
          codigo: "javi-martinez",
          dorsal: 9,
          enClubDesde: "2022",
          contratoHasta: "2026",
          logros: ["Pichichi Primera RFEF 2023/24"],
          stats: {
            partidos: 35,
            goles: 22,
            asistencias: 6,
            minutos: 2980,
            amarillas: 5,
            rojas: 0,
          },
        },
      ],

      cuerpoTecnico: [
        {
          id: 1,
          nombre: "Carlos Mendoza",
          cargo: "Entrenador Principal",
          imagen: "https://picsum.photos/seed/coach1-23/400/450",
          descripcion: "Temporada de consolidación.",
          esPrincipal: true,
          estadisticas: {
            partidos: 38,
            victorias: 18,
            empates: 10,
            derrotas: 10,
          },
        },
      ],

      partidosJugados: [
        {
          id: 101,
          jornada: 38,
          fecha: "2024-05-19",
          local: "Real Oviedo",
          visitante: "Cultural Soria",
          golesLocal: 3,
          golesVisitante: 1,
          resultado: "V",
        },
        {
          id: 102,
          jornada: 37,
          fecha: "2024-05-12",
          local: "Racing Ferrol",
          visitante: "Real Oviedo",
          golesLocal: 2,
          golesVisitante: 2,
          resultado: "E",
        },
      ],
    },

    // ===================================
    // TEMPORADA 2022/23
    // ===================================
    "2022-23": {
      competicion: "Segunda RFEF",
      grupo: "Grupo I",

      estadisticasEquipo: {
        posicion: 1,
        partidosJugados: 34,
        victorias: 22,
        empates: 6,
        derrotas: 6,
        golesFavor: 62,
        golesContra: 28,
      },

      jugadores: [
        {
          id: "miguel-angel-torres",
          codigo: "miguel-angel-torres",
          dorsal: 1,
          enClubDesde: "2022",
          contratoHasta: "2024",
          stats: {
            partidos: 34,
            goles: 0,
            asistencias: 0,
            minutos: 3060,
            amarillas: 2,
            rojas: 0,
          },
        },
        {
          id: "raul-fernandez",
          codigo: "raul-fernandez",
          dorsal: 5,
          enClubDesde: "2021",
          contratoHasta: "2023",
          stats: {
            partidos: 28,
            goles: 3,
            asistencias: 1,
            minutos: 2480,
            amarillas: 4,
            rojas: 0,
          },
        },
        {
          id: "jorge-martin",
          codigo: "jorge-martin",
          dorsal: 3,
          enClubDesde: "2022",
          contratoHasta: "2024",
          stats: {
            partidos: 26,
            goles: 0,
            asistencias: 7,
            minutos: 2200,
            amarillas: 3,
            rojas: 0,
          },
        },
        {
          id: "javi-martinez",
          codigo: "javi-martinez",
          dorsal: 9,
          enClubDesde: "2022",
          contratoHasta: "2025",
          logros: ["Ascenso a Primera RFEF"],
          stats: {
            partidos: 32,
            goles: 18,
            asistencias: 5,
            minutos: 2750,
            amarillas: 4,
            rojas: 0,
          },
        },
      ],

      cuerpoTecnico: [
        {
          id: 1,
          nombre: "Carlos Mendoza",
          cargo: "Entrenador Principal",
          imagen: "https://picsum.photos/seed/coach1-22/400/450",
          descripcion: "Primera temporada. Ascenso.",
          esPrincipal: true,
          estadisticas: {
            partidos: 34,
            victorias: 22,
            empates: 6,
            derrotas: 6,
          },
        },
      ],

      partidosJugados: [
        {
          id: 201,
          jornada: 34,
          fecha: "2023-05-14",
          local: "Real Oviedo",
          visitante: "Atlético Vergara",
          golesLocal: 3,
          golesVisitante: 0,
          resultado: "V",
        },
        {
          id: 202,
          jornada: 33,
          fecha: "2023-05-07",
          local: "Cultural Soria",
          visitante: "Real Oviedo",
          golesLocal: 1,
          golesVisitante: 1,
          resultado: "E",
        },
      ],
    },
  },

  // ===================================
  // DATOS GENERALES
  // ===================================

  calendario: [
    {
      id: 1,
      jornada: 24,
      fecha: "2025-01-26",
      hora: "18:00",
      local: "Real Oviedo",
      visitante: "UD Rosaleda",
      estadio: "Carlos Tartiere",
      esProximo: true,
    },
  ],
  patrocinadores: [{ id: 1, nombre: "Grupo Norte" }],
  proximoPartido: {
    jornada: 24,
    competicion: "Primera RFEF",
    fecha: "2025-01-26",
    hora: "18:00",
    local: "Real Oviedo",
    localSiglas: "OVI",
    visitante: "UD Rosaleda",
    visitanteSiglas: "UDR",
    estadio: "Carlos Tartiere",
  },

  // ===================================
  // JUEGOS (Menú Multimedia)
  // ===================================
  juegos: [
    {
      id: "quiz",
      titulo: "Quiz Carbayón",
      descripcion: "¿Cuánto sabes de la historia del club?",
      imagen: "https://i.postimg.cc/3J1wMxw4/Quiz.webp",
      enlace: "juegos/quiz.html",
      esEspecial: true,
    },
    {
      id: "memoria",
      titulo: "Juego de Memoria",
      descripcion: "Encuentra las parejas de escudos y jugadores.",
      imagen: "https://picsum.photos/seed/memory-game/400/300",
      enlace: "#",
      esEspecial: false,
    },
    {
      id: "penaltis",
      titulo: "Lanzamiento de Penaltis",
      descripcion: "Elige la esquina y marca el gol decisivo.",
      imagen: "https://picsum.photos/seed/penalty-game/400/300",
      enlace: "#",
      esEspecial: false,
    },
  ],

  // ===================================
  // VIDEOS (Resúmenes de Partidos)
  // ===================================
  videos: [
    {
      id: 1,
      jornada: 12,
      titulo: "R. Oviedo vs Elche CF",
      fecha: "2024-10-27",
      videoId: "C5E4g_uy9PE",
    },
    {
      id: 2,
      jornada: 11,
      titulo: "Eibar vs R. Oviedo",
      fecha: "2024-10-20",
      videoId: "dQw4w9WgXcQ",
    },
    {
      id: 3,
      jornada: 10,
      titulo: "R. Oviedo vs Racing",
      fecha: "2024-10-13",
      videoId: "dQw4w9WgXcQ",
    },
  ],

  // ===================================
  // PRIMERA DIVISIÓN - HISTÓRICO
  // ===================================
  primeraDivisionHistorico: {
    "2025-26": {
      nombre: "2025/26",
      competicion: "LaLiga EA Sports",
      jornadas: [
        {
          numero: 1,
          fecha: "15-18 AGO",
          partidos: [
            {
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              estado: "finalizado",
              escudoLocal: "",
              escudoVisitante: "",
              goleadores: [
                { jugador: "Javi Martínez", minuto: "23'", equipo: "local" },
                { jugador: "En-Nesyri", minuto: "45'", equipo: "visitante" },
                { jugador: "Rubén Cano", minuto: "78'", equipo: "local" },
              ],
            },
            {
              local: "FC Barcelona",
              visitante: "Valencia CF",
              golesLocal: 3,
              golesVisitante: 0,
              estado: "finalizado",
              goleadores: [
                { jugador: "Lewandowski", minuto: "12'", equipo: "local" },
                { jugador: "Lamine Yamal", minuto: "34'", equipo: "local" },
              ],
            },
            {
              local: "Real Madrid",
              visitante: "Atlético de Madrid",
              golesLocal: 1,
              golesVisitante: 1,
              estado: "finalizado",
              goleadores: [
                { jugador: "Bellingham", minuto: "56'", equipo: "local" },
                { jugador: "Griezmann", minuto: "72'", equipo: "visitante" },
              ],
            },
          ],
        },
        {
          numero: 2,
          fecha: "22-25 AGO",
          partidos: [
            {
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              estado: "finalizado",
              goleadores: [
                { jugador: "Bellingham", minuto: "56'", equipo: "local" },
                { jugador: "Aarón", minuto: "89'", equipo: "visitante" },
              ],
            },
            {
              local: "Sevilla FC",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 2,
              estado: "finalizado",
              goleadores: [
                { jugador: "Pedri", minuto: "23'", equipo: "visitante" },
                { jugador: "Raphinha", minuto: "67'", equipo: "visitante" },
              ],
            },
          ],
        },
        {
          numero: 3,
          fecha: "29 AGO - 01 SEP",
          partidos: [
            {
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              estado: "finalizado",
              goleadores: [
                { jugador: "Javi Martínez", minuto: "12'", equipo: "local" },
                { jugador: "Javi Martínez", minuto: "45'", equipo: "local" },
                { jugador: "Stuani", minuto: "56'", equipo: "visitante" },
                { jugador: "Stuani", minuto: "78'", equipo: "visitante" },
                { jugador: "Luis García", minuto: "90'", equipo: "local" },
              ],
            },
          ],
        },
      ],
    },
    "2001-02": {
      nombre: "2001/02",
      competicion: "La Liga",
      jornadas: [
        {
          numero: 1,
          fecha: "25-27 AGO 2001",
          partidos: [
            {
              local: "Real Oviedo",
              visitante: "R.C. Celta de Vigo",
              golesLocal: 1,
              golesVisitante: 2,
              estado: "finalizado",
              goleadores: [
                { jugador: "Oli", minuto: "34'", equipo: "local" },
                { jugador: "Mostovoi", minuto: "12'", equipo: "visitante" },
                { jugador: "Karpin", minuto: "78'", equipo: "visitante" },
              ],
            },
          ],
        },
      ],
    },
  },
};

// ===================================
// FUNCIONES DE AYUDA
// ===================================

function getTemporada(seasonId) {
  return (
    CLUB_DATA.temporadas[seasonId] ||
    CLUB_DATA.temporadas[CLUB_DATA.temporadaActual]
  );
}

function getJugadorById(id, seasonId) {
  const temporada = getTemporada(seasonId);

  // Buscar el registro variable en la temporada (por codigo o id)
  const datoTemp =
    temporada.jugadores.find((j) => j.codigo === id) ||
    temporada.jugadores.find((j) => j.id === id) ||
    temporada.jugadores.find((j) => j.id === parseInt(id)); // compatibilidad hacia atrás

  if (!datoTemp) return null;

  // Recuperar datos fijos del maestro
  const datoMaestro = CLUB_DATA.jugadoresMaestro[datoTemp.codigo] || {};

  // Fusionar: el maestro pone la base, la temporada sobreescribe lo variable
  return { ...datoMaestro, ...datoTemp };
}

window.CLUB_DATA = CLUB_DATA;
window.getTemporada = getTemporada;
window.getJugadorById = getJugadorById;
