/* ===================================
   DATOS DEL CLUB - REAL OVIEDO
   =================================== */

const CLUB_DATA = {
  // Información del club
  club: {
    nombre: "Real Oviedo",
    nombreCorto: "Real Oviedo",
    logo: "https://i.postimg.cc/yYcPrs6f/Oviedo.png",
    siglas: "OVI",
    fundacion: 1926,
    estadio: "Estadio Carlos Tartiere",
    capacidadEstadio: 30500,
    ciudad: "Oviedo",
    direccion: "Calle Carlos Tartiere s/n, 33013 Oviedo",
    telefono: "985 111 111",
    email: "info@realoviedo.es",
  },

  // Temporada actual (por defecto)
  temporadaActual: "2025-26",

  // Lista de temporadas disponibles
  temporadasDisponibles: [
    { id: "2025-26", nombre: "2025/26", actual: true },
    { id: "2024-25", nombre: "2024/25", actual: false },
    { id: "2023-24", nombre: "2023/24", actual: false },
    { id: "2022-23", nombre: "2022/23", actual: false },
  ],

  // Datos por temporada
  temporadas: {
    // ===================================
    // TEMPORADA 2025/26
    // ===================================
    "2025-26": {
      competicion: "Primera División",
      grupo: "null",

      estadisticasEquipo: {
        posicion: 20,
        partidosJugados: 29,
        victorias: 4,
        empates: 9,
        derrotas: 16,
        golesFavor: 20,
        golesContra: 48,
      },

      jugadores: [
        // PORTEROS
        {
          id: "aaron-escandell-banacloche",
          codigo: "aaron-escandell-banacloche",
          nombre: "Aarón",
          apellidos: "Escandell Banacloche",
          nombreCompleto: "Aarón Escandell Banacloche",
          apodo: "Aarón",
          dorsal: 13,
          posicion: "Portero",
          posicionCorta: "POR",
          edad: 30,
          altura: 1.84,
          nacionalidad: "Española",
          lugarNacimiento: "Carcagente, Valencia",
          fechaNacimiento: "1995-09-27",
          enClubDesde: "2024",
          contratoHasta: "2027",
          imagen: "https://i.postimg.cc/hvxDQPg1/Aarón_PNG_(3).webp",
          stats: {
            partidos: 29,
            goles: 48,
            asistencias: 0,
            minutos: 2610,
            amarillas: 2,
            rojas: 0,
            desglose: {
              "Primera División": {
                partidos: 24,
                goles: 40,
                asistencias: 0,
                minutos: 2160,
                amarillas: 1,
                rojas: 0,
              },
              "Copa del Rey": {
                partidos: 3,
                goles: 5,
                asistencias: 0,
                minutos: 270,
                amarillas: 1,
                rojas: 0,
              },
              "Competición Internacional": {
                partidos: 2,
                goles: 3,
                asistencias: 0,
                minutos: 180,
                amarillas: 0,
                rojas: 0,
              },
            },
          },
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-17",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-31",
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: 4,
              competicion: "Primera División",
              fecha: "2025-09-14",
              local: "Athletic Club",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 5,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 6,
              competicion: "Primera División",
              fecha: "2025-09-28",
              local: "Osasuna",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-10-05",
              local: "Real Oviedo",
              visitante: "Getafe CF",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 8,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-19",
              local: "Valencia CF",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 9,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-26",
              local: "Real Oviedo",
              visitante: "Celta de Vigo",
              golesLocal: 2,
              golesVisitante: 2,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: 10,
              competicion: "Primera División",
              fecha: "2025-11-02",
              local: "Villarreal CF",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: "Octavos",
              competicion: "Copa del Rey",
              fecha: "2025-11-06",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 12,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-09",
              local: "Real Oviedo",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 4,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 13,
              jornada: 12,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 13,
              competicion: "Primera División",
              fecha: "2025-11-30",
              local: "Real Oviedo",
              visitante: "Real Sociedad",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 14,
              competicion: "Primera División",
              fecha: "2025-12-07",
              local: "Atlético Madrid",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 16,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Real Oviedo",
              visitante: "Espanyol",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 16,
              competicion: "Primera División",
              fecha: "2025-12-21",
              local: "Elche CF",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 18,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 19,
              jornada: 18,
              competicion: "Primera División",
              fecha: "2026-01-11",
              local: "Girona FC",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 20,
              jornada: 19,
              competicion: "Primera División",
              fecha: "2026-01-18",
              local: "Real Oviedo",
              visitante: "Athletic Club",
              golesLocal: 0,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 21,
              jornada: 20,
              competicion: "Primera División",
              fecha: "2026-01-25",
              local: "Rayo Vallecano",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 22,
              jornada: "Cuartos",
              competicion: "Copa del Rey",
              fecha: "2026-01-29",
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 23,
              jornada: 21,
              competicion: "Primera División",
              fecha: "2026-02-01",
              local: "Real Oviedo",
              visitante: "Osasuna",
              golesLocal: 0,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 24,
              jornada: 22,
              competicion: "Primera División",
              fecha: "2026-02-08",
              local: "Getafe CF",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 25,
              jornada: 23,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Valencia CF",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 26,
              jornada: 24,
              competicion: "Primera División",
              fecha: "2026-02-22",
              local: "Celta de Vigo",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 27,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-03-01",
              local: "Real Oviedo",
              visitante: "Villarreal CF",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 28,
              jornada: 26,
              competicion: "Primera División",
              fecha: "2026-03-08",
              local: "FC Barcelona",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 29,
              jornada: 27,
              competicion: "Primera División",
              fecha: "2026-03-15",
              local: "Real Oviedo",
              visitante: "Alavés",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 30,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-22",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 31,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-29",
              local: "Levante UD",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "horatiu-alexandru-moldovan",
          codigo: "horatiu-alexandru-moldovan",
          nombre: "Horațiu Alexandru",
          apellidos: "Moldovan",
          nombreCompleto: "Horațiu Alexandru Moldovan",
          apodo: "Moldovan",
          dorsal: 1,
          posicion: "Portero",
          posicionCorta: "POR",
          edad: 28,
          altura: 1.86,
          nacionalidad: "Rumana",
          lugarNacimiento: "Cluj-Napoca, Transilvania",
          fechaNacimiento: "1998-01-20",
          enClubDesde: "2025",
          contratoHasta: "2026",
          imagen: "https://i.postimg.cc/sgPM0mk4/Moldovan_PNG_(2).webp",
          stats: {
            partidos: 1,
            goles: 4,
            asistencias: 0,
            minutos: 0,
            amarillas: 0,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "miguel-de-jesus-narvaez-lopez",
          codigo: "miguel-de-jesus-narvaez-lopez",
          nombre: "Miguel de Jesús",
          apellidos: "Narváez López",
          nombreCompleto: "Miguel de Jesús Narváez López",
          apodo: "Narváez",
          dorsal: 26,
          posicion: "Portero",
          posicionCorta: "POR",
          edad: 24,
          altura: 1.88,
          nacionalidad: "Española",
          lugarNacimiento: "Badajoz, Badajoz",
          fechaNacimiento: "2002-04-29",
          enClubDesde: "2024",
          contratoHasta: "2027",
          imagen: "https://i.postimg.cc/XJqXqbps/Narváez_PNG.webp",
          stats: {
            partidos: 0,
            goles: 0,
            asistencias: 0,
            minutos: 0,
            amarillas: 0,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        // DEFENSAS
        {
          id: "adrian-picos",
          codigo: "adrian-picos",
          nombre: "Adrián",
          apellidos: "Picos Menéndez",
          nombreCompleto: "Adrián Picos",
          dorsal: 4,
          posicion: "Central",
          posicionCorta: "DC",
          edad: 29,
          altura: 1.85,
          peso: 80,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Santander, Cantabria",
          fechaNacimiento: "1995-06-18",
          enClubDesde: "2022",
          contratoHasta: "2025",
          imagen: "https://i.postimg.cc/MZ1ZJxQr/Adri_Lopes_PNG.png",
          stats: {
            partidos: 23,
            goles: 3,
            asistencias: 1,
            minutos: 2045,
            amarillas: 5,
            rojas: 0,
          },
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-17",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-31",
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: 4,
              competicion: "Primera División",
              fecha: "2025-09-14",
              local: "Athletic Club",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 5,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 6,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-10-05",
              local: "Real Oviedo",
              visitante: "Getafe CF",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-19",
              local: "Valencia CF",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 8,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-26",
              local: "Real Oviedo",
              visitante: "Celta de Vigo",
              golesLocal: 2,
              golesVisitante: 2,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 9,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-09",
              local: "Real Oviedo",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 4,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: 12,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: 14,
              competicion: "Primera División",
              fecha: "2025-12-07",
              local: "Atlético Madrid",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 12,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Real Oviedo",
              visitante: "Espanyol",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 13,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 22,
              competicion: "Primera División",
              fecha: "2026-02-08",
              local: "Getafe CF",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 23,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Valencia CF",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 16,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-03-01",
              local: "Real Oviedo",
              visitante: "Villarreal CF",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 27,
              competicion: "Primera División",
              fecha: "2026-03-15",
              local: "Real Oviedo",
              visitante: "Alavés",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 18,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-22",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 19,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-29",
              local: "Levante UD",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "victor-marquez",
          codigo: "victor-marquez",
          nombre: "Víctor",
          apellidos: "Márquez López",
          nombreCompleto: "Víctor Márquez",
          dorsal: 5,
          posicion: "Central",
          posicionCorta: "DC",
          edad: 27,
          altura: 1.82,
          peso: 77,
          pie: "Izquierdo",
          nacionalidad: "Española",
          lugarNacimiento: "León",
          fechaNacimiento: "1997-09-30",
          enClubDesde: "2023",
          contratoHasta: "2026",
          imagen: "https://picsum.photos/seed/df3-24/400/500",
          stats: {
            partidos: 22,
            goles: 1,
            asistencias: 2,
            minutos: 1890,
            amarillas: 4,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "sergio-nunez",
          codigo: "sergio-nunez",
          nombre: "Sergio",
          apellidos: "Núñez Pérez",
          nombreCompleto: "Sergio Núñez",
          dorsal: 3,
          posicion: "Lateral Izquierdo",
          posicionCorta: "LI",
          edad: 24,
          altura: 1.76,
          peso: 70,
          pie: "Izquierdo",
          nacionalidad: "Española",
          lugarNacimiento: "Madrid",
          fechaNacimiento: "2000-02-14",
          enClubDesde: "2024",
          contratoHasta: "2026",
          imagen: "https://picsum.photos/seed/df4-24/400/500",
          stats: {
            partidos: 18,
            goles: 0,
            asistencias: 4,
            minutos: 1420,
            amarillas: 2,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "borja-trujillo",
          codigo: "borja-trujillo",
          nombre: "Borja",
          apellidos: "Trujillo Fernández",
          nombreCompleto: "Borja Trujillo",
          dorsal: 15,
          posicion: "Central",
          posicionCorta: "DC",
          edad: 25,
          altura: 1.88,
          peso: 83,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Gijón, Asturias",
          fechaNacimiento: "1999-08-05",
          enClubDesde: "2023",
          contratoHasta: "2025",
          imagen: "https://picsum.photos/seed/df5-24/400/500",
          stats: {
            partidos: 12,
            goles: 0,
            asistencias: 0,
            minutos: 890,
            amarillas: 2,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "alvaro-santos",
          codigo: "alvaro-santos",
          nombre: "Álvaro",
          apellidos: "Santos Díaz",
          nombreCompleto: "Álvaro Santos",
          dorsal: 6,
          posicion: "Mediocentro Defensivo",
          posicionCorta: "MCD",
          edad: 30,
          altura: 1.8,
          peso: 75,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Sevilla",
          fechaNacimiento: "1994-12-10",
          enClubDesde: "2022",
          contratoHasta: "2025",
          imagen: "https://picsum.photos/seed/mf1-24/400/500",
          stats: {
            partidos: 23,
            goles: 1,
            asistencias: 2,
            minutos: 1980,
            amarillas: 8,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "nacho-ruiz",
          codigo: "nacho-ruiz",
          nombre: "Nacho",
          apellidos: "Ruiz Martínez",
          nombreCompleto: "Nacho Ruiz",
          dorsal: 8,
          posicion: "Centrocampista",
          posicionCorta: "MC",
          edad: 26,
          altura: 1.77,
          peso: 72,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Valencia",
          fechaNacimiento: "1998-04-25",
          enClubDesde: "2023",
          contratoHasta: "2026",
          imagen: "https://picsum.photos/seed/mf2-24/400/500",
          stats: {
            partidos: 22,
            goles: 5,
            asistencias: 6,
            minutos: 1750,
            amarillas: 3,
            rojas: 0,
          },
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-17",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-31",
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 2,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 5,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-10-05",
              local: "Real Oviedo",
              visitante: "Getafe CF",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 75,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-19",
              local: "Valencia CF",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-26",
              local: "Real Oviedo",
              visitante: "Celta de Vigo",
              golesLocal: 2,
              golesVisitante: 2,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 8,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-09",
              local: "Real Oviedo",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 4,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 9,
              jornada: 12,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: "Octavos",
              competicion: "Copa del Rey",
              fecha: "2025-11-06",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Real Oviedo",
              visitante: "Espanyol",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 12,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 13,
              jornada: 22,
              competicion: "Primera División",
              fecha: "2026-02-08",
              local: "Getafe CF",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 68,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 23,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Valencia CF",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-03-01",
              local: "Real Oviedo",
              visitante: "Villarreal CF",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 16,
              jornada: 27,
              competicion: "Primera División",
              fecha: "2026-03-15",
              local: "Real Oviedo",
              visitante: "Alavés",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-22",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 18,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-29",
              local: "Levante UD",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "pedro-leal",
          codigo: "pedro-leal",
          nombre: "Pedro",
          apellidos: "Leal García",
          nombreCompleto: "Pedro Leal",
          dorsal: 10,
          posicion: "Mediapunta",
          posicionCorta: "MP",
          edad: 28,
          altura: 1.74,
          peso: 68,
          pie: "Izquierdo",
          nacionalidad: "Española",
          lugarNacimiento: "Barcelona",
          fechaNacimiento: "1996-07-08",
          enClubDesde: "2022",
          contratoHasta: "2025",
          imagen: "https://picsum.photos/seed/mf3-24/400/500",
          stats: {
            partidos: 21,
            goles: 8,
            asistencias: 5,
            minutos: 1680,
            amarillas: 2,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "ivan-pacheco",
          codigo: "ivan-pacheco",
          nombre: "Iván",
          apellidos: "Pacheco Fernández",
          nombreCompleto: "Iván Pacheco",
          dorsal: 16,
          posicion: "Centrocampista",
          posicionCorta: "MC",
          edad: 23,
          altura: 1.75,
          peso: 70,
          pie: "Izquierdo",
          nacionalidad: "Española",
          lugarNacimiento: "Salamanca",
          fechaNacimiento: "2001-03-18",
          enClubDesde: "2025",
          contratoHasta: "2027",
          imagen: "https://picsum.photos/seed/mf4-24/400/500",
          stats: {
            partidos: 5,
            goles: 0,
            asistencias: 1,
            minutos: 210,
            amarillas: 0,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "antonio-suarez",
          codigo: "antonio-suarez",
          nombre: "Antonio",
          apellidos: "Suárez Vega",
          nombreCompleto: "Antonio Suárez",
          dorsal: 14,
          posicion: "Centrocampista",
          posicionCorta: "MC",
          edad: 26,
          altura: 1.8,
          peso: 75,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Zamora",
          fechaNacimiento: "1998-09-22",
          enClubDesde: "2023",
          contratoHasta: "2025",
          imagen: "https://picsum.photos/seed/mf5-24/400/500",
          stats: {
            partidos: 15,
            goles: 2,
            asistencias: 3,
            minutos: 1100,
            amarillas: 3,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "javi-martinez",
          codigo: "javi-martinez",
          nombre: "Javi",
          apellidos: "Martínez Fernández",
          nombreCompleto: "Javi Martínez",
          dorsal: 9,
          posicion: "Delantero Centro",
          posicionCorta: "DC",
          edad: 27,
          altura: 1.82,
          peso: 75,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Gijón, Asturias",
          fechaNacimiento: "1997-03-15",
          enClubDesde: "2022",
          contratoHasta: "2026",
          imagen: "https://picsum.photos/seed/fw1-24/400/500",
          esCapitan: true,
          stats: {
            partidos: 23,
            goles: 14,
            asistencias: 4,
            minutos: 1892,
            amarillas: 4,
            rojas: 0,
          },
          logros: ["Pichichi Primera RFEF 2023/24", "Capitán del equipo"],
          partidos: [
            {
              id: 1,
              jornada: 1,
              competicion: "Primera División",
              fecha: "2025-08-17",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 2,
              jornada: 2,
              competicion: "Primera División",
              fecha: "2025-08-24",
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 3,
              jornada: 3,
              competicion: "Primera División",
              fecha: "2025-08-31",
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 2,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 4,
              jornada: 4,
              competicion: "Primera División",
              fecha: "2025-09-14",
              local: "Athletic Club",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 5,
              jornada: 5,
              competicion: "Primera División",
              fecha: "2025-09-21",
              local: "Real Oviedo",
              visitante: "Rayo Vallecano",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 6,
              jornada: 6,
              competicion: "Primera División",
              fecha: "2025-09-28",
              local: "Osasuna",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 0,
              resultado: "D",
              minutos: 72,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 7,
              jornada: 7,
              competicion: "Primera División",
              fecha: "2025-10-05",
              local: "Real Oviedo",
              visitante: "Getafe CF",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 8,
              jornada: 8,
              competicion: "Primera División",
              fecha: "2025-10-19",
              local: "Valencia CF",
              visitante: "Real Oviedo",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 9,
              jornada: 9,
              competicion: "Primera División",
              fecha: "2025-10-26",
              local: "Real Oviedo",
              visitante: "Celta de Vigo",
              golesLocal: 2,
              golesVisitante: 2,
              resultado: "E",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 10,
              jornada: "Octavos",
              competicion: "Copa del Rey",
              fecha: "2025-11-06",
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 11,
              jornada: 11,
              competicion: "Primera División",
              fecha: "2025-11-09",
              local: "Real Oviedo",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 4,
              resultado: "D",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 12,
              jornada: 12,
              competicion: "Primera División",
              fecha: "2025-11-23",
              local: "Alavés",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 1,
              amarilla: true,
              roja: false,
            },
            {
              id: 13,
              jornada: 14,
              competicion: "Primera División",
              fecha: "2025-12-07",
              local: "Atlético Madrid",
              visitante: "Real Oviedo",
              golesLocal: 3,
              golesVisitante: 1,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 14,
              jornada: 15,
              competicion: "Primera División",
              fecha: "2025-12-14",
              local: "Real Oviedo",
              visitante: "Espanyol",
              golesLocal: 2,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 15,
              jornada: 17,
              competicion: "Primera División",
              fecha: "2026-01-04",
              local: "Real Oviedo",
              visitante: "Real Betis",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: true,
              roja: false,
            },
            {
              id: 16,
              jornada: 22,
              competicion: "Primera División",
              fecha: "2026-02-08",
              local: "Getafe CF",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 2,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 17,
              jornada: 23,
              competicion: "Primera División",
              fecha: "2026-02-15",
              local: "Real Oviedo",
              visitante: "Valencia CF",
              golesLocal: 2,
              golesVisitante: 1,
              resultado: "V",
              minutos: 90,
              goles: 2,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 18,
              jornada: 25,
              competicion: "Primera División",
              fecha: "2026-03-01",
              local: "Real Oviedo",
              visitante: "Villarreal CF",
              golesLocal: 1,
              golesVisitante: 1,
              resultado: "E",
              minutos: 78,
              goles: 0,
              asistencias: 1,
              amarilla: false,
              roja: false,
            },
            {
              id: 19,
              jornada: 27,
              competicion: "Primera División",
              fecha: "2026-03-15",
              local: "Real Oviedo",
              visitante: "Alavés",
              golesLocal: 1,
              golesVisitante: 0,
              resultado: "V",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 20,
              jornada: 28,
              competicion: "Primera División",
              fecha: "2026-03-22",
              local: "Real Sociedad",
              visitante: "Real Oviedo",
              golesLocal: 0,
              golesVisitante: 0,
              resultado: "E",
              minutos: 90,
              goles: 0,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
            {
              id: 21,
              jornada: 29,
              competicion: "Primera División",
              fecha: "2026-03-29",
              local: "Levante UD",
              visitante: "Real Oviedo",
              golesLocal: 4,
              golesVisitante: 2,
              resultado: "D",
              minutos: 90,
              goles: 1,
              asistencias: 0,
              amarilla: false,
              roja: false,
            },
          ],
          redes: { instagram: "#", twitter: "#" },
          seleccion: {
            pais: "España",
            bandera: "https://flagcdn.com/w40/es.png",
            datos: [
              { categoria: "Absoluta", partidos: 28, goles: 3 },
              { categoria: "U21", partidos: 15, goles: 2 },
            ],
          },
        },
        {
          id: "ruben-cano",
          codigo: "ruben-cano",
          nombre: "Rubén",
          apellidos: "Cano Pérez",
          nombreCompleto: "Rubén Cano",
          dorsal: 7,
          posicion: "Extremo Derecho",
          posicionCorta: "ED",
          edad: 25,
          altura: 1.73,
          peso: 67,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Bilbao, Vizcaya",
          fechaNacimiento: "1999-05-28",
          enClubDesde: "2023",
          contratoHasta: "2025",
          imagen: "https://picsum.photos/seed/fw2-24/400/500",
          stats: {
            partidos: 20,
            goles: 6,
            asistencias: 8,
            minutos: 1450,
            amarillas: 1,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "luis-garcia",
          codigo: "luis-garcia",
          nombre: "Luis",
          apellidos: "García Rodríguez",
          nombreCompleto: "Luis 'Lucho' García",
          dorsal: 11,
          posicion: "Extremo Izquierdo",
          posicionCorta: "EI",
          edad: 24,
          altura: 1.76,
          peso: 71,
          pie: "Izquierdo",
          nacionalidad: "Argentino",
          lugarNacimiento: "Buenos Aires",
          fechaNacimiento: "2000-09-18",
          enClubDesde: "2024",
          contratoHasta: "2026",
          imagen: "https://picsum.photos/seed/fw3-24/400/500",
          stats: {
            partidos: 22,
            goles: 7,
            asistencias: 9,
            minutos: 1580,
            amarillas: 2,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "diego-lopez",
          codigo: "diego-lopez",
          nombre: "Diego",
          apellidos: "López Sánchez",
          nombreCompleto: "Diego 'Chicho' López",
          dorsal: 17,
          posicion: "Delantero",
          posicionCorta: "DC",
          edad: 22,
          altura: 1.79,
          peso: 76,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Santander, Cantabria",
          fechaNacimiento: "2002-01-05",
          enClubDesde: "2024",
          contratoHasta: "2026",
          imagen: "https://picsum.photos/seed/fw4-24/400/500",
          stats: {
            partidos: 12,
            goles: 3,
            asistencias: 1,
            minutos: 580,
            amarillas: 0,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
      ],

      cuerpoTecnico: [
        {
          id: 1,
          nombre: "Carlos Mendoza",
          cargo: "Entrenador Principal",
          imagen: "https://picsum.photos/seed/coach1/400/450",
          descripcion:
            "Licenciado en Educación Física con más de 15 años de experiencia.",
          esPrincipal: true,
          estadisticas: {
            partidos: 89,
            victorias: 46,
            empates: 22,
            derrotas: 21,
          },
        },
        {
          id: 2,
          nombre: "Roberto Vázquez",
          cargo: "Segundo Entrenador",
          imagen: "https://picsum.photos/seed/coach2/400/450",
          descripcion: "Especialista en análisis táctico.",
          esPrincipal: false,
        },
      ],

      partidosJugados: [
        {
          id: 1,
          jornada: 23,
          competicion: "Primera División",
          fecha: "2025-01-19",
          local: "Real Oviedo",
          visitante: "Atlético Vergara",
          golesLocal: 2,
          golesVisitante: 1,
          resultado: "V",
        },
        {
          id: 2,
          jornada: "Octavos",
          competicion: "Copa del Rey",
          fecha: "2025-01-15",
          local: "Real Oviedo",
          visitante: "Sevilla FC",
          golesLocal: 1,
          golesVisitante: 0,
          resultado: "V",
        },
      ],
    },

    // ===================================
    // TEMPORADA 2023/24
    // ===================================
    "2023-24": {
      competicion: "Primera RFEF",
      grupo: "Grupo I",

      estadisticasEquipo: {
        posicion: 4,
        partidosJugados: 38,
        victorias: 18,
        empates: 10,
        derrotas: 10,
        golesFavor: 56,
        golesContra: 35,
      },

      jugadores: [
        {
          id: "miguel-angel-torres",
          codigo: "miguel-angel-torres",
          nombre: "Miguel Ángel",
          apellidos: "Torres García",
          nombreCompleto: "Miguel Ángel Torres",
          dorsal: 1,
          posicion: "Portero",
          posicionCorta: "POR",
          edad: 27,
          altura: 1.87,
          peso: 82,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Oviedo, Asturias",
          fechaNacimiento: "1997-03-15",
          enClubDesde: "2022",
          contratoHasta: "2025",
          imagen: "https://picsum.photos/seed/gk1-23/400/500",
          stats: {
            partidos: 36,
            goles: 0,
            asistencias: 0,
            minutos: 3240,
            amarillas: 3,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "adrian-picos",
          codigo: "adrian-picos",
          nombre: "Adrián",
          apellidos: "Picos Menéndez",
          nombreCompleto: "Adrián Picos",
          dorsal: 4,
          posicion: "Central",
          posicionCorta: "DC",
          edad: 28,
          altura: 1.85,
          peso: 80,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Santander, Cantabria",
          fechaNacimiento: "1995-06-18",
          enClubDesde: "2022",
          contratoHasta: "2025",
          imagen: "https://i.postimg.cc/MZ1ZJxQr/Adri_Lopes_PNG.png",
          stats: {
            partidos: 35,
            goles: 4,
            asistencias: 2,
            minutos: 3080,
            amarillas: 7,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "javi-martinez",
          codigo: "javi-martinez",
          nombre: "Javi",
          apellidos: "Martínez Fernández",
          nombreCompleto: "Javi Martínez",
          dorsal: 9,
          posicion: "Delantero Centro",
          posicionCorta: "DC",
          edad: 26,
          altura: 1.82,
          peso: 75,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Gijón, Asturias",
          fechaNacimiento: "1997-03-15",
          enClubDesde: "2022",
          contratoHasta: "2026",
          imagen: "https://picsum.photos/seed/fw1-23/400/500",
          stats: {
            partidos: 35,
            goles: 22,
            asistencias: 6,
            minutos: 2980,
            amarillas: 5,
            rojas: 0,
          },
          logros: ["Pichichi Primera RFEF 2023/24"],
          redes: { instagram: "#", twitter: "#" },
          seleccion: {
            pais: "España",
            bandera: "https://flagcdn.com/w40/es.png",
            datos: [
              { categoria: "Absoluta", partidos: 28, goles: 3 },
              { categoria: "U21", partidos: 15, goles: 2 },
            ],
          },
        },
      ],

      cuerpoTecnico: [
        {
          id: 1,
          nombre: "Carlos Mendoza",
          cargo: "Entrenador Principal",
          imagen: "https://picsum.photos/seed/coach1-23/400/450",
          descripcion: "Temporada de consolidación.",
          esPrincipal: true,
          estadisticas: {
            partidos: 38,
            victorias: 18,
            empates: 10,
            derrotas: 10,
          },
        },
      ],

      partidosJugados: [
        {
          id: 101,
          jornada: 38,
          fecha: "2024-05-19",
          local: "Real Oviedo",
          visitante: "Cultural Soria",
          golesLocal: 3,
          golesVisitante: 1,
          resultado: "V",
        },
        {
          id: 102,
          jornada: 37,
          fecha: "2024-05-12",
          local: "Racing Ferrol",
          visitante: "Real Oviedo",
          golesLocal: 2,
          golesVisitante: 2,
          resultado: "E",
        },
      ],
    },

    // ===================================
    // TEMPORADA 2022/23
    // ===================================
    "2022-23": {
      competicion: "Segunda RFEF",
      grupo: "Grupo I",

      estadisticasEquipo: {
        posicion: 1,
        partidosJugados: 34,
        victorias: 22,
        empates: 6,
        derrotas: 6,
        golesFavor: 62,
        golesContra: 28,
      },

      jugadores: [
        {
          id: "miguel-angel-torres",
          codigo: "miguel-angel-torres",
          nombre: "Miguel Ángel",
          apellidos: "Torres García",
          nombreCompleto: "Miguel Ángel Torres",
          dorsal: 1,
          posicion: "Portero",
          posicionCorta: "POR",
          edad: 26,
          altura: 1.87,
          peso: 82,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Oviedo, Asturias",
          fechaNacimiento: "1997-03-15",
          enClubDesde: "2022",
          contratoHasta: "2024",
          imagen: "https://picsum.photos/seed/gk1-22/400/500",
          stats: {
            partidos: 34,
            goles: 0,
            asistencias: 0,
            minutos: 3060,
            amarillas: 2,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
        },
        {
          id: "raul-fernandez",
          codigo: "raul-fernandez",
          nombre: "Raúl",
          apellidos: "Fernández Soto",
          nombreCompleto: "Raúl Fernández",
          dorsal: 5,
          posicion: "Central",
          posicionCorta: "DC",
          edad: 31,
          altura: 1.84,
          peso: 79,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Gijón, Asturias",
          fechaNacimiento: "1993-02-14",
          enClubDesde: "2021",
          contratoHasta: "2023",
          imagen: "https://picsum.photos/seed/df3-22/400/500",
          stats: {
            partidos: 28,
            goles: 3,
            asistencias: 1,
            minutos: 2480,
            amarillas: 4,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: "#" },
          fallecido: true,
          fechaFallecimiento: "2024-05-15",
        },
        {
          id: "jorge-martin",
          codigo: "jorge-martin",
          nombre: "Jorge",
          apellidos: "Martín Díaz",
          nombreCompleto: "Jorge Martín",
          dorsal: 3,
          posicion: "Lateral Izquierdo",
          posicionCorta: "LI",
          edad: 25,
          peso: 71,
          pie: "Izquierdo",
          nacionalidad: "Española",
          lugarNacimiento: "Zamora",
          fechaNacimiento: "1998-11-30",
          enClubDesde: "2022",
          contratoHasta: "2024",
          imagen: "https://picsum.photos/seed/df4-22/400/500",
          stats: {
            partidos: 26,
            goles: 0,
            asistencias: 7,
            minutos: 2200,
            amarillas: 3,
            rojas: 0,
          },
          redes: { instagram: "#", twitter: null },
        },
        {
          id: "javi-martinez",
          codigo: "javi-martinez",
          nombre: "Javi",
          apellidos: "Martínez Fernández",
          nombreCompleto: "Javi Martínez",
          dorsal: 9,
          posicion: "Delantero Centro",
          posicionCorta: "DC",
          edad: 25,
          altura: 1.82,
          peso: 75,
          pie: "Derecho",
          nacionalidad: "Española",
          lugarNacimiento: "Gijón, Asturias",
          fechaNacimiento: "1997-03-15",
          enClubDesde: "2022",
          contratoHasta: "2025",
          imagen: "https://picsum.photos/seed/fw1-22/400/500",
          stats: {
            partidos: 32,
            goles: 18,
            asistencias: 5,
            minutos: 2750,
            amarillas: 4,
            rojas: 0,
          },
          logros: ["Ascenso a Primera RFEF"],
          redes: { instagram: "#", twitter: "#" },
          seleccion: {
            pais: "España",
            bandera: "https://flagcdn.com/w40/es.png",
            datos: [
              { categoria: "Absoluta", partidos: 28, goles: 3 },
              { categoria: "U21", partidos: 15, goles: 2 },
            ],
          },
        },
      ],

      cuerpoTecnico: [
        {
          id: 1,
          nombre: "Carlos Mendoza",
          cargo: "Entrenador Principal",
          imagen: "https://picsum.photos/seed/coach1-22/400/450",
          descripcion: "Primera temporada. Ascenso.",
          esPrincipal: true,
          estadisticas: {
            partidos: 34,
            victorias: 22,
            empates: 6,
            derrotas: 6,
          },
        },
      ],

      partidosJugados: [
        {
          id: 201,
          jornada: 34,
          fecha: "2023-05-14",
          local: "Real Oviedo",
          visitante: "Atlético Vergara",
          golesLocal: 3,
          golesVisitante: 0,
          resultado: "V",
        },
        {
          id: 202,
          jornada: 33,
          fecha: "2023-05-07",
          local: "Cultural Soria",
          visitante: "Real Oviedo",
          golesLocal: 1,
          golesVisitante: 1,
          resultado: "E",
        },
      ],
    },
  },

  // ===================================
  // DATOS GENERALES
  // ===================================

  calendario: [
    {
      id: 1,
      jornada: 24,
      fecha: "2025-01-26",
      hora: "18:00",
      local: "Real Oviedo",
      visitante: "UD Rosaleda",
      estadio: "Carlos Tartiere",
      esProximo: true,
    },
  ],
  noticias: [
    {
      id: 1,
      titulo: "El Real Oviedo encadena victorias",
      resumen: "Gran momento de forma.",
      categoria: "Primer Equipo",
      fecha: "2025-01-24",
      imagen: "https://picsum.photos/seed/news1/800/500",
      esPrincipal: true,
    },
  ],
  patrocinadores: [{ id: 1, nombre: "Grupo Norte" }],
  proximoPartido: {
    jornada: 24,
    competicion: "Primera RFEF",
    fecha: "2025-01-26",
    hora: "18:00",
    local: "Real Oviedo",
    localSiglas: "OVI",
    visitante: "UD Rosaleda",
    visitanteSiglas: "UDR",
    estadio: "Carlos Tartiere",
  },

  // ===================================
  // JUEGOS (Menú Multimedia)
  // ===================================
  juegos: [
    {
      id: "quiz",
      titulo: "Quiz Carbayón",
      descripcion: "¿Cuánto sabes de la historia del club?",
      imagen: "https://i.postimg.cc/3J1wMxw4/Quiz.webp",
      enlace: "juegos/quiz.html",
      esEspecial: true,
    },
    {
      id: "memoria",
      titulo: "Juego de Memoria",
      descripcion: "Encuentra las parejas de escudos y jugadores.",
      imagen: "https://picsum.photos/seed/memory-game/400/300",
      enlace: "#",
      esEspecial: false,
    },
    {
      id: "penaltis",
      titulo: "Lanzamiento de Penaltis",
      descripcion: "Elige la esquina y marca el gol decisivo.",
      imagen: "https://picsum.photos/seed/penalty-game/400/300",
      enlace: "#",
      esEspecial: false,
    },
  ],

  // ===================================
  // VIDEOS (Resúmenes de Partidos)
  // ===================================
  videos: [
    {
      id: 1,
      jornada: 12,
      titulo: "R. Oviedo vs Elche CF",
      fecha: "2024-10-27",
      videoId: "C5E4g_uy9PE", // Tu ID real de YouTube
    },
    {
      id: 2,
      jornada: 11,
      titulo: "Eibar vs R. Oviedo",
      fecha: "2024-10-20",
      videoId: "dQw4w9WgXcQ", // ID de ejemplo (cambiar por real)
    },
    {
      id: 3,
      jornada: 10,
      titulo: "R. Oviedo vs Racing",
      fecha: "2024-10-13",
      videoId: "dQw4w9WgXcQ", // ID de ejemplo (cambiar por real)
    },
  ],

  // ===================================
  // PRIMERA DIVISIÓN - HISTÓRICO
  // ===================================
  primeraDivisionHistorico: {
    "2025-26": {
      nombre: "2025/26",
      competicion: "LaLiga EA Sports",
      jornadas: [
        {
          numero: 1,
          fecha: "15-18 AGO",
          partidos: [
            {
              local: "Real Oviedo",
              visitante: "Sevilla FC",
              golesLocal: 2,
              golesVisitante: 1,
              estado: "finalizado",
              escudoLocal: "", // Dejar vacío para placeholder
              escudoVisitante: "", // Dejar vacío para placeholder
              goleadores: [
                { jugador: "Javi Martínez", minuto: "23'", equipo: "local" },
                { jugador: "En-Nesyri", minuto: "45'", equipo: "visitante" },
                { jugador: "Rubén Cano", minuto: "78'", equipo: "local" },
              ],
            },
            {
              local: "FC Barcelona",
              visitante: "Valencia CF",
              golesLocal: 3,
              golesVisitante: 0,
              estado: "finalizado",
              goleadores: [
                { jugador: "Lewandowski", minuto: "12'", equipo: "local" },
                { jugador: "Lamine Yamal", minuto: "34'", equipo: "local" },
              ],
            },
            {
              local: "Real Madrid",
              visitante: "Atlético de Madrid",
              golesLocal: 1,
              golesVisitante: 1,
              estado: "finalizado",
              goleadores: [
                { jugador: "Bellingham", minuto: "56'", equipo: "local" },
                { jugador: "Griezmann", minuto: "72'", equipo: "visitante" },
              ],
            },
          ],
        },
        {
          numero: 2,
          fecha: "22-25 AGO",
          partidos: [
            {
              local: "Real Madrid",
              visitante: "Real Oviedo",
              golesLocal: 1,
              golesVisitante: 1,
              estado: "finalizado",
              goleadores: [
                { jugador: "Bellingham", minuto: "56'", equipo: "local" },
                { jugador: "Aarón", minuto: "89'", equipo: "visitante" },
              ],
            },
            {
              local: "Sevilla FC",
              visitante: "FC Barcelona",
              golesLocal: 0,
              golesVisitante: 2,
              estado: "finalizado",
              goleadores: [
                { jugador: "Pedri", minuto: "23'", equipo: "visitante" },
                { jugador: "Raphinha", minuto: "67'", equipo: "visitante" },
              ],
            },
          ],
        },
        {
          numero: 3,
          fecha: "29 AGO - 01 SEP",
          partidos: [
            {
              local: "Real Oviedo",
              visitante: "Girona FC",
              golesLocal: 3,
              golesVisitante: 2,
              estado: "finalizado",
              goleadores: [
                { jugador: "Javi Martínez", minuto: "12'", equipo: "local" },
                { jugador: "Javi Martínez", minuto: "45'", equipo: "local" },
                { jugador: "Stuani", minuto: "56'", equipo: "visitante" },
                { jugador: "Stuani", minuto: "78'", equipo: "visitante" },
                { jugador: "Luis García", minuto: "90'", equipo: "local" },
              ],
            },
          ],
        },
      ],
    },
    "2001-02": {
      nombre: "2001/02",
      competicion: "La Liga",
      jornadas: [
        {
          numero: 1,
          fecha: "25-27 AGO 2001",
          partidos: [
            {
              local: "Real Oviedo",
              visitante: "Celta de Vigo",
              golesLocal: 1,
              golesVisitante: 2,
              estado: "finalizado",
              goleadores: [
                { jugador: "Oli", minuto: "34'", equipo: "local" },
                { jugador: "Mostovoi", minuto: "12'", equipo: "visitante" },
                { jugador: "Karpin", minuto: "78'", equipo: "visitante" },
              ],
            },
          ],
        },
      ],
    },
  },
};

// ===================================
// FUNCIONES DE AYUDA
// ===================================

function getTemporada(seasonId) {
  return (
    CLUB_DATA.temporadas[seasonId] ||
    CLUB_DATA.temporadas[CLUB_DATA.temporadaActual]
  );
}

function getJugadorById(id, seasonId) {
  const temporada = getTemporada(seasonId);

  // 1. Busca primero por código (slug) - esto funcionará con los nuevos IDs string
  const porCodigo = temporada.jugadores.find((j) => j.codigo === id);
  if (porCodigo) return porCodigo;

  // 2. Busca por ID exacto (ahora es string, ej: "miguel-angel-torres")
  const porId = temporada.jugadores.find((j) => j.id === id);
  if (porId) return porId;

  // 3. Compatibilidad hacia atrás: por si hay enlaces antiguos guardados con números (ej: id=101)
  return temporada.jugadores.find((j) => j.id === parseInt(id));
}

// Nota: formatearFecha ya está definida en app.js, no es necesaria aquí duplicada.

window.CLUB_DATA = CLUB_DATA;
window.getTemporada = getTemporada;
window.getJugadorById = getJugadorById;
